# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fly_net.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1882, 999)
        MainWindow.setMinimumSize(QtCore.QSize(1810, 911))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.DataLoadTab = QtWidgets.QWidget()
        self.DataLoadTab.setObjectName("DataLoadTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.DataLoadTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.DataLoadTab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 8)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 2)
        self.line_16 = QtWidgets.QFrame(self.frame_2)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 12, 0, 1, 8)
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 13, 0, 1, 8)
        spacerItem = QtWidgets.QSpacerItem(116, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(151, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(133, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 7, 4, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 3)
        self.movie_table = QtWidgets.QTableWidget(self.frame_2)
        self.movie_table.setObjectName("movie_table")
        self.movie_table.setColumnCount(0)
        self.movie_table.setRowCount(0)
        self.gridLayout.addWidget(self.movie_table, 8, 0, 1, 8)
        self.seq_folder_disp = QtWidgets.QLineEdit(self.frame_2)
        self.seq_folder_disp.setObjectName("seq_folder_disp")
        self.gridLayout.addWidget(self.seq_folder_disp, 3, 0, 1, 4)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 8)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 11, 0, 1, 8)
        self.load_seq_btn = QtWidgets.QPushButton(self.frame_2)
        self.load_seq_btn.setObjectName("load_seq_btn")
        self.gridLayout.addWidget(self.load_seq_btn, 14, 5, 1, 3)
        self.select_seq_btn = QtWidgets.QPushButton(self.frame_2)
        self.select_seq_btn.setObjectName("select_seq_btn")
        self.gridLayout.addWidget(self.select_seq_btn, 3, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(173, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 14, 0, 1, 4)
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 9, 0, 1, 8)
        self.calib_folder_disp = QtWidgets.QLineEdit(self.frame_2)
        self.calib_folder_disp.setObjectName("calib_folder_disp")
        self.gridLayout.addWidget(self.calib_folder_disp, 5, 0, 1, 4)
        self.select_calib_btn = QtWidgets.QPushButton(self.frame_2)
        self.select_calib_btn.setObjectName("select_calib_btn")
        self.gridLayout.addWidget(self.select_calib_btn, 5, 6, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 6)
        spacerItem5 = QtWidgets.QSpacerItem(78, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 10, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 0, 1, 1)
        self.trigger_mode_combo = QtWidgets.QComboBox(self.frame_2)
        self.trigger_mode_combo.setObjectName("trigger_mode_combo")
        self.gridLayout.addWidget(self.trigger_mode_combo, 10, 1, 1, 4)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.img_viewer_1 = ImgViewer1(self.frame_3)
        self.img_viewer_1.setMinimumSize(QtCore.QSize(1404, 551))
        self.img_viewer_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_viewer_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_viewer_1.setObjectName("img_viewer_1")
        self.verticalLayout_3.addWidget(self.img_viewer_1)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(1389, 211))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 211))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(91, 171))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 171))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.movie_spin_1 = QtWidgets.QSpinBox(self.frame_6)
        self.movie_spin_1.setObjectName("movie_spin_1")
        self.verticalLayout.addWidget(self.movie_spin_1)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.frame_spin_1 = QtWidgets.QSpinBox(self.frame_6)
        self.frame_spin_1.setObjectName("frame_spin_1")
        self.verticalLayout.addWidget(self.frame_spin_1)
        self.gridLayout_13.addWidget(self.frame_6, 0, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        self.frame_11.setMinimumSize(QtCore.QSize(171, 171))
        self.frame_11.setMaximumSize(QtCore.QSize(171, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_33 = QtWidgets.QLabel(self.frame_11)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 0, 0, 1, 2)
        self.line_14 = QtWidgets.QFrame(self.frame_11)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_7.addWidget(self.line_14, 1, 0, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.frame_11)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 2, 0, 1, 1)
        self.Nu_crop_spin = QtWidgets.QSpinBox(self.frame_11)
        self.Nu_crop_spin.setObjectName("Nu_crop_spin")
        self.gridLayout_7.addWidget(self.Nu_crop_spin, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_11)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 3, 0, 1, 1)
        self.Nv_crop_spin = QtWidgets.QSpinBox(self.frame_11)
        self.Nv_crop_spin.setObjectName("Nv_crop_spin")
        self.gridLayout_7.addWidget(self.Nv_crop_spin, 3, 1, 1, 1)
        self.man_select_btn = QtWidgets.QRadioButton(self.frame_11)
        self.man_select_btn.setObjectName("man_select_btn")
        self.gridLayout_7.addWidget(self.man_select_btn, 4, 0, 1, 2)
        self.auto_select_btn = QtWidgets.QRadioButton(self.frame_11)
        self.auto_select_btn.setObjectName("auto_select_btn")
        self.gridLayout_7.addWidget(self.auto_select_btn, 5, 0, 1, 2)
        self.gridLayout_13.addWidget(self.frame_11, 0, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setMinimumSize(QtCore.QSize(131, 171))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 171))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.body_thresh_spin = QtWidgets.QSpinBox(self.frame_8)
        self.body_thresh_spin.setObjectName("body_thresh_spin")
        self.verticalLayout_8.addWidget(self.body_thresh_spin)
        self.label_14 = QtWidgets.QLabel(self.frame_8)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.max_dist_COM_spin = QtWidgets.QSpinBox(self.frame_8)
        self.max_dist_COM_spin.setObjectName("max_dist_COM_spin")
        self.verticalLayout_8.addWidget(self.max_dist_COM_spin)
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.min_len_spin = QtWidgets.QSpinBox(self.frame_8)
        self.min_len_spin.setObjectName("min_len_spin")
        self.verticalLayout_8.addWidget(self.min_len_spin)
        self.gridLayout_13.addWidget(self.frame_8, 0, 2, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame_5)
        self.frame_16.setMinimumSize(QtCore.QSize(171, 171))
        self.frame_16.setMaximumSize(QtCore.QSize(171, 171))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_36 = QtWidgets.QLabel(self.frame_16)
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 0, 0, 1, 2)
        self.line_15 = QtWidgets.QFrame(self.frame_16)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_11.addWidget(self.line_15, 1, 0, 1, 2)
        self.label_44 = QtWidgets.QLabel(self.frame_16)
        self.label_44.setObjectName("label_44")
        self.gridLayout_11.addWidget(self.label_44, 2, 0, 1, 1)
        self.crop_x_spin = QtWidgets.QDoubleSpinBox(self.frame_16)
        self.crop_x_spin.setObjectName("crop_x_spin")
        self.gridLayout_11.addWidget(self.crop_x_spin, 2, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_16)
        self.label_45.setObjectName("label_45")
        self.gridLayout_11.addWidget(self.label_45, 3, 0, 1, 1)
        self.crop_y_spin = QtWidgets.QDoubleSpinBox(self.frame_16)
        self.crop_y_spin.setObjectName("crop_y_spin")
        self.gridLayout_11.addWidget(self.crop_y_spin, 3, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame_16)
        self.label_46.setObjectName("label_46")
        self.gridLayout_11.addWidget(self.label_46, 4, 0, 1, 1)
        self.crop_z_spin = QtWidgets.QDoubleSpinBox(self.frame_16)
        self.crop_z_spin.setObjectName("crop_z_spin")
        self.gridLayout_11.addWidget(self.crop_z_spin, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem6, 5, 0, 1, 2)
        self.gridLayout_13.addWidget(self.frame_16, 0, 3, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.frame_5)
        self.frame_21.setMinimumSize(QtCore.QSize(141, 171))
        self.frame_21.setMaximumSize(QtCore.QSize(141, 171))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_21)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_47 = QtWidgets.QLabel(self.frame_21)
        self.label_47.setObjectName("label_47")
        self.gridLayout_12.addWidget(self.label_47, 0, 0, 1, 2)
        self.line_18 = QtWidgets.QFrame(self.frame_21)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_12.addWidget(self.line_18, 1, 0, 1, 2)
        self.label_48 = QtWidgets.QLabel(self.frame_21)
        self.label_48.setObjectName("label_48")
        self.gridLayout_12.addWidget(self.label_48, 2, 0, 1, 1)
        self.cam_mask_spin = QtWidgets.QSpinBox(self.frame_21)
        self.cam_mask_spin.setObjectName("cam_mask_spin")
        self.gridLayout_12.addWidget(self.cam_mask_spin, 2, 1, 1, 1)
        self.add_mask_btn = QtWidgets.QPushButton(self.frame_21)
        self.add_mask_btn.setObjectName("add_mask_btn")
        self.gridLayout_12.addWidget(self.add_mask_btn, 3, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(108, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem7, 4, 0, 1, 2)
        self.remove_masks_btn = QtWidgets.QPushButton(self.frame_21)
        self.remove_masks_btn.setObjectName("remove_masks_btn")
        self.gridLayout_12.addWidget(self.remove_masks_btn, 5, 0, 1, 2)
        self.gridLayout_13.addWidget(self.frame_21, 0, 4, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.frame_5)
        self.frame_20.setMinimumSize(QtCore.QSize(151, 171))
        self.frame_20.setMaximumSize(QtCore.QSize(151, 16777215))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_40 = QtWidgets.QLabel(self.frame_20)
        self.label_40.setObjectName("label_40")
        self.gridLayout_10.addWidget(self.label_40, 0, 0, 1, 2)
        self.line_17 = QtWidgets.QFrame(self.frame_20)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_10.addWidget(self.line_17, 1, 0, 1, 2)
        self.label_41 = QtWidgets.QLabel(self.frame_20)
        self.label_41.setObjectName("label_41")
        self.gridLayout_10.addWidget(self.label_41, 2, 0, 1, 1)
        self.cam_uv_shift_spin = QtWidgets.QSpinBox(self.frame_20)
        self.cam_uv_shift_spin.setObjectName("cam_uv_shift_spin")
        self.gridLayout_10.addWidget(self.cam_uv_shift_spin, 2, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.frame_20)
        self.label_42.setObjectName("label_42")
        self.gridLayout_10.addWidget(self.label_42, 3, 0, 1, 1)
        self.u_uv_shift_spin = QtWidgets.QSpinBox(self.frame_20)
        self.u_uv_shift_spin.setObjectName("u_uv_shift_spin")
        self.gridLayout_10.addWidget(self.u_uv_shift_spin, 3, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_20)
        self.label_43.setObjectName("label_43")
        self.gridLayout_10.addWidget(self.label_43, 4, 0, 1, 1)
        self.v_uv_shift_spin = QtWidgets.QSpinBox(self.frame_20)
        self.v_uv_shift_spin.setObjectName("v_uv_shift_spin")
        self.gridLayout_10.addWidget(self.v_uv_shift_spin, 4, 1, 1, 1)
        self.set_uv_shift_btn = QtWidgets.QPushButton(self.frame_20)
        self.set_uv_shift_btn.setObjectName("set_uv_shift_btn")
        self.gridLayout_10.addWidget(self.set_uv_shift_btn, 5, 0, 1, 2)
        self.gridLayout_13.addWidget(self.frame_20, 0, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(240, 148, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem8, 0, 6, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setMinimumSize(QtCore.QSize(441, 171))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 171))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.frame_9)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 1, 0, 1, 2)
        self.save_fldr_disp = QtWidgets.QLineEdit(self.frame_9)
        self.save_fldr_disp.setObjectName("save_fldr_disp")
        self.gridLayout_3.addWidget(self.save_fldr_disp, 2, 0, 1, 1)
        self.select_save_fldr_btn = QtWidgets.QPushButton(self.frame_9)
        self.select_save_fldr_btn.setObjectName("select_save_fldr_btn")
        self.gridLayout_3.addWidget(self.select_save_fldr_btn, 2, 1, 1, 1)
        self.crop_seq_calc_progress = QtWidgets.QProgressBar(self.frame_9)
        self.crop_seq_calc_progress.setProperty("value", 24)
        self.crop_seq_calc_progress.setObjectName("crop_seq_calc_progress")
        self.gridLayout_3.addWidget(self.crop_seq_calc_progress, 3, 0, 1, 1)
        self.calc_crop_seq_btn = QtWidgets.QPushButton(self.frame_9)
        self.calc_crop_seq_btn.setObjectName("calc_crop_seq_btn")
        self.gridLayout_3.addWidget(self.calc_crop_seq_btn, 3, 1, 1, 1)
        self.load_crop_seq_btn = QtWidgets.QPushButton(self.frame_9)
        self.load_crop_seq_btn.setObjectName("load_crop_seq_btn")
        self.gridLayout_3.addWidget(self.load_crop_seq_btn, 4, 1, 1, 1)
        self.load_file_disp = QtWidgets.QLineEdit(self.frame_9)
        self.load_file_disp.setObjectName("load_file_disp")
        self.gridLayout_3.addWidget(self.load_file_disp, 4, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_9, 0, 7, 1, 1)
        self.frame_slider = QtWidgets.QSlider(self.frame_5)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.gridLayout_13.addWidget(self.frame_slider, 1, 0, 1, 8)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_7.addWidget(self.frame)
        self.tabWidget.addTab(self.DataLoadTab, "")
        self.TrackTab = QtWidgets.QWidget()
        self.TrackTab.setObjectName("TrackTab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.TrackTab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.TrackTab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMinimumSize(QtCore.QSize(1751, 591))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img_viewer_2 = ImgViewer2(self.frame_7)
        self.img_viewer_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_viewer_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_viewer_2.setObjectName("img_viewer_2")
        self.horizontalLayout_2.addWidget(self.img_viewer_2)
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        self.frame_12.setMinimumSize(QtCore.QSize(241, 571))
        self.frame_12.setMaximumSize(QtCore.QSize(241, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_32 = QtWidgets.QLabel(self.frame_12)
        self.label_32.setObjectName("label_32")
        self.gridLayout_9.addWidget(self.label_32, 0, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.frame_12)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_9.addWidget(self.line_11, 1, 0, 1, 4)
        self.outlier_frame_table = QtWidgets.QTableWidget(self.frame_12)
        self.outlier_frame_table.setMinimumSize(QtCore.QSize(221, 311))
        self.outlier_frame_table.setObjectName("outlier_frame_table")
        self.outlier_frame_table.setColumnCount(0)
        self.outlier_frame_table.setRowCount(0)
        self.gridLayout_9.addWidget(self.outlier_frame_table, 2, 0, 1, 4)
        self.label_37 = QtWidgets.QLabel(self.frame_12)
        self.label_37.setObjectName("label_37")
        self.gridLayout_9.addWidget(self.label_37, 3, 0, 1, 1)
        self.outlier_spin = QtWidgets.QSpinBox(self.frame_12)
        self.outlier_spin.setObjectName("outlier_spin")
        self.gridLayout_9.addWidget(self.outlier_spin, 3, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 4, 0, 1, 1)
        self.update_outlier_btn = QtWidgets.QPushButton(self.frame_12)
        self.update_outlier_btn.setObjectName("update_outlier_btn")
        self.gridLayout_9.addWidget(self.update_outlier_btn, 4, 1, 1, 3)
        self.line_13 = QtWidgets.QFrame(self.frame_12)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_9.addWidget(self.line_13, 5, 0, 1, 4)
        self.outlier_fix_progress = QtWidgets.QProgressBar(self.frame_12)
        self.outlier_fix_progress.setMinimumSize(QtCore.QSize(221, 25))
        self.outlier_fix_progress.setProperty("value", 24)
        self.outlier_fix_progress.setObjectName("outlier_fix_progress")
        self.gridLayout_9.addWidget(self.outlier_fix_progress, 6, 0, 1, 4)
        self.label_38 = QtWidgets.QLabel(self.frame_12)
        self.label_38.setObjectName("label_38")
        self.gridLayout_9.addWidget(self.label_38, 7, 0, 1, 1)
        self.auto_fix_btn = QtWidgets.QPushButton(self.frame_12)
        self.auto_fix_btn.setObjectName("auto_fix_btn")
        self.gridLayout_9.addWidget(self.auto_fix_btn, 7, 3, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.frame_12)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout_9.addWidget(self.line_24, 8, 0, 1, 4)
        self.label_69 = QtWidgets.QLabel(self.frame_12)
        self.label_69.setObjectName("label_69")
        self.gridLayout_9.addWidget(self.label_69, 9, 0, 1, 4)
        self.train_net_progress = QtWidgets.QProgressBar(self.frame_12)
        self.train_net_progress.setMinimumSize(QtCore.QSize(221, 25))
        self.train_net_progress.setProperty("value", 24)
        self.train_net_progress.setObjectName("train_net_progress")
        self.gridLayout_9.addWidget(self.train_net_progress, 10, 0, 1, 4)
        spacerItem10 = QtWidgets.QSpacerItem(119, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 11, 0, 1, 2)
        self.train_net_btn = QtWidgets.QPushButton(self.frame_12)
        self.train_net_btn.setMinimumSize(QtCore.QSize(89, 25))
        self.train_net_btn.setObjectName("train_net_btn")
        self.gridLayout_9.addWidget(self.train_net_btn, 11, 2, 1, 2)
        self.line_23 = QtWidgets.QFrame(self.frame_12)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout_9.addWidget(self.line_23, 12, 0, 1, 4)
        self.label_39 = QtWidgets.QLabel(self.frame_12)
        self.label_39.setObjectName("label_39")
        self.gridLayout_9.addWidget(self.label_39, 13, 0, 1, 4)
        spacerItem11 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 14, 0, 1, 3)
        self.add_lbl_btn = QtWidgets.QPushButton(self.frame_12)
        self.add_lbl_btn.setObjectName("add_lbl_btn")
        self.gridLayout_9.addWidget(self.add_lbl_btn, 14, 3, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setMinimumSize(QtCore.QSize(1751, 201))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 201))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_13 = QtWidgets.QFrame(self.frame_10)
        self.frame_13.setMinimumSize(QtCore.QSize(1731, 161))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 161))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setMinimumSize(QtCore.QSize(181, 141))
        self.frame_14.setMaximumSize(QtCore.QSize(181, 16777215))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_14)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_14)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 0, 1, 1, 1)
        self.movie_spin_2 = QtWidgets.QSpinBox(self.frame_14)
        self.movie_spin_2.setObjectName("movie_spin_2")
        self.gridLayout_5.addWidget(self.movie_spin_2, 1, 0, 1, 1)
        self.seq_nr_spin = QtWidgets.QSpinBox(self.frame_14)
        self.seq_nr_spin.setObjectName("seq_nr_spin")
        self.gridLayout_5.addWidget(self.seq_nr_spin, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_14)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.img_view_btn = QtWidgets.QRadioButton(self.frame_14)
        self.img_view_btn.setObjectName("img_view_btn")
        self.gridLayout_5.addWidget(self.img_view_btn, 2, 1, 1, 1)
        self.frame_spin_2 = QtWidgets.QSpinBox(self.frame_14)
        self.frame_spin_2.setObjectName("frame_spin_2")
        self.gridLayout_5.addWidget(self.frame_spin_2, 3, 0, 1, 1)
        self.seg_view_btn = QtWidgets.QRadioButton(self.frame_14)
        self.seg_view_btn.setObjectName("seg_view_btn")
        self.gridLayout_5.addWidget(self.seg_view_btn, 3, 1, 1, 1)
        self.gridLayout_15.addWidget(self.frame_14, 0, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setMinimumSize(QtCore.QSize(181, 141))
        self.frame_15.setMaximumSize(QtCore.QSize(196, 16777215))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame_15)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.select_mdl_btn = QtWidgets.QPushButton(self.frame_15)
        self.select_mdl_btn.setMinimumSize(QtCore.QSize(89, 25))
        self.select_mdl_btn.setObjectName("select_mdl_btn")
        self.gridLayout_2.addWidget(self.select_mdl_btn, 0, 1, 1, 2)
        self.line_6 = QtWidgets.QFrame(self.frame_15)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 1, 0, 1, 3)
        self.model_disp = QtWidgets.QLineEdit(self.frame_15)
        self.model_disp.setMinimumSize(QtCore.QSize(161, 25))
        self.model_disp.setObjectName("model_disp")
        self.gridLayout_2.addWidget(self.model_disp, 2, 0, 1, 3)
        self.mdl_view_btn = QtWidgets.QRadioButton(self.frame_15)
        self.mdl_view_btn.setObjectName("mdl_view_btn")
        self.gridLayout_2.addWidget(self.mdl_view_btn, 3, 0, 1, 2)
        self.off_view_btn = QtWidgets.QRadioButton(self.frame_15)
        self.off_view_btn.setObjectName("off_view_btn")
        self.gridLayout_2.addWidget(self.off_view_btn, 3, 2, 1, 1)
        self.single_view_btn = QtWidgets.QRadioButton(self.frame_15)
        self.single_view_btn.setObjectName("single_view_btn")
        self.gridLayout_2.addWidget(self.single_view_btn, 4, 0, 1, 2)
        self.gridLayout_15.addWidget(self.frame_15, 0, 1, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame_13)
        self.frame_17.setMinimumSize(QtCore.QSize(361, 141))
        self.frame_17.setMaximumSize(QtCore.QSize(361, 16777215))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.frame_17)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(47, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 0, 3, 1, 2)
        self.mdl_combo = QtWidgets.QComboBox(self.frame_17)
        self.mdl_combo.setObjectName("mdl_combo")
        self.gridLayout_4.addWidget(self.mdl_combo, 0, 5, 1, 3)
        self.line_7 = QtWidgets.QFrame(self.frame_17)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_4.addWidget(self.line_7, 1, 0, 1, 8)
        self.label_16 = QtWidgets.QLabel(self.frame_17)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 2, 1)
        self.qx_spin = QtWidgets.QDoubleSpinBox(self.frame_17)
        self.qx_spin.setObjectName("qx_spin")
        self.gridLayout_4.addWidget(self.qx_spin, 2, 1, 2, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_17)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 2, 2, 2, 2)
        self.tx_spin = QtWidgets.QDoubleSpinBox(self.frame_17)
        self.tx_spin.setObjectName("tx_spin")
        self.gridLayout_4.addWidget(self.tx_spin, 2, 4, 2, 2)
        self.scale_spin = QtWidgets.QDoubleSpinBox(self.frame_17)
        self.scale_spin.setObjectName("scale_spin")
        self.gridLayout_4.addWidget(self.scale_spin, 2, 7, 2, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_17)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 3, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_17)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 4, 0, 1, 1)
        self.qy_spin = QtWidgets.QDoubleSpinBox(self.frame_17)
        self.qy_spin.setObjectName("qy_spin")
        self.gridLayout_4.addWidget(self.qy_spin, 4, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_17)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 4, 2, 1, 2)
        self.ty_spin = QtWidgets.QDoubleSpinBox(self.frame_17)
        self.ty_spin.setObjectName("ty_spin")
        self.gridLayout_4.addWidget(self.ty_spin, 4, 4, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.frame_17)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 4, 6, 1, 1)
        self.xi_spin = QtWidgets.QDoubleSpinBox(self.frame_17)
        self.xi_spin.setObjectName("xi_spin")
        self.gridLayout_4.addWidget(self.xi_spin, 4, 7, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_17)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 5, 0, 1, 1)
        self.qz_spin = QtWidgets.QDoubleSpinBox(self.frame_17)
        self.qz_spin.setObjectName("qz_spin")
        self.gridLayout_4.addWidget(self.qz_spin, 5, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_17)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 5, 2, 1, 2)
        self.tz_spin = QtWidgets.QDoubleSpinBox(self.frame_17)
        self.tz_spin.setObjectName("tz_spin")
        self.gridLayout_4.addWidget(self.tz_spin, 5, 4, 1, 2)
        self.reset_state_btn = QtWidgets.QPushButton(self.frame_17)
        self.reset_state_btn.setObjectName("reset_state_btn")
        self.gridLayout_4.addWidget(self.reset_state_btn, 5, 6, 1, 2)
        self.gridLayout_15.addWidget(self.frame_17, 0, 2, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.frame_13)
        self.frame_18.setMinimumSize(QtCore.QSize(291, 141))
        self.frame_18.setMaximumSize(QtCore.QSize(291, 141))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_24 = QtWidgets.QLabel(self.frame_18)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 0, 0, 1, 2)
        self.line_9 = QtWidgets.QFrame(self.frame_18)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_6.addWidget(self.line_9, 1, 0, 1, 4)
        self.label_25 = QtWidgets.QLabel(self.frame_18)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 2, 0, 1, 1)
        self.network_combo = QtWidgets.QComboBox(self.frame_18)
        self.network_combo.setObjectName("network_combo")
        self.gridLayout_6.addWidget(self.network_combo, 2, 2, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.frame_18)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 3, 0, 1, 1)
        self.weights_disp = QtWidgets.QLineEdit(self.frame_18)
        self.weights_disp.setObjectName("weights_disp")
        self.gridLayout_6.addWidget(self.weights_disp, 3, 1, 1, 2)
        self.select_weights_btn = QtWidgets.QPushButton(self.frame_18)
        self.select_weights_btn.setObjectName("select_weights_btn")
        self.gridLayout_6.addWidget(self.select_weights_btn, 3, 3, 1, 1)
        self.predict_btn = QtWidgets.QPushButton(self.frame_18)
        self.predict_btn.setObjectName("predict_btn")
        self.gridLayout_6.addWidget(self.predict_btn, 4, 0, 1, 4)
        self.gridLayout_15.addWidget(self.frame_18, 0, 3, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame_13)
        self.frame_19.setMinimumSize(QtCore.QSize(221, 142))
        self.frame_19.setMaximumSize(QtCore.QSize(221, 142))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_28 = QtWidgets.QLabel(self.frame_19)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 0, 1, 2)
        self.line_10 = QtWidgets.QFrame(self.frame_19)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_8.addWidget(self.line_10, 1, 0, 1, 2)
        self.label_29 = QtWidgets.QLabel(self.frame_19)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 2, 0, 1, 1)
        self.N_particles_spin = QtWidgets.QSpinBox(self.frame_19)
        self.N_particles_spin.setMinimumSize(QtCore.QSize(81, 26))
        self.N_particles_spin.setObjectName("N_particles_spin")
        self.gridLayout_8.addWidget(self.N_particles_spin, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_19)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 3, 0, 1, 1)
        self.N_iter_spin = QtWidgets.QSpinBox(self.frame_19)
        self.N_iter_spin.setObjectName("N_iter_spin")
        self.gridLayout_8.addWidget(self.N_iter_spin, 3, 1, 1, 1)
        self.pso_search_btn = QtWidgets.QPushButton(self.frame_19)
        self.pso_search_btn.setObjectName("pso_search_btn")
        self.gridLayout_8.addWidget(self.pso_search_btn, 4, 0, 1, 2)
        self.gridLayout_15.addWidget(self.frame_19, 0, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(368, 138, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem13, 0, 5, 1, 1)
        self.frame_22 = QtWidgets.QFrame(self.frame_13)
        self.frame_22.setMinimumSize(QtCore.QSize(421, 141))
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 141))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_22)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_31 = QtWidgets.QLabel(self.frame_22)
        self.label_31.setObjectName("label_31")
        self.gridLayout_14.addWidget(self.label_31, 0, 0, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem14, 0, 2, 1, 1)
        self.load_tracked_btn = QtWidgets.QPushButton(self.frame_22)
        self.load_tracked_btn.setObjectName("load_tracked_btn")
        self.gridLayout_14.addWidget(self.load_tracked_btn, 0, 3, 1, 2)
        self.line_12 = QtWidgets.QFrame(self.frame_22)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_14.addWidget(self.line_12, 1, 0, 1, 5)
        self.label_49 = QtWidgets.QLabel(self.frame_22)
        self.label_49.setObjectName("label_49")
        self.gridLayout_14.addWidget(self.label_49, 2, 0, 1, 1)
        self.batch_size_spin = QtWidgets.QSpinBox(self.frame_22)
        self.batch_size_spin.setObjectName("batch_size_spin")
        self.gridLayout_14.addWidget(self.batch_size_spin, 2, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(120, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem15, 2, 2, 1, 1)
        self.analyze_btn = QtWidgets.QPushButton(self.frame_22)
        self.analyze_btn.setObjectName("analyze_btn")
        self.gridLayout_14.addWidget(self.analyze_btn, 2, 4, 1, 1)
        self.analysis_progress = QtWidgets.QProgressBar(self.frame_22)
        self.analysis_progress.setMinimumSize(QtCore.QSize(401, 51))
        self.analysis_progress.setProperty("value", 24)
        self.analysis_progress.setObjectName("analysis_progress")
        self.gridLayout_14.addWidget(self.analysis_progress, 3, 0, 1, 5)
        self.gridLayout_15.addWidget(self.frame_22, 0, 6, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_13)
        self.frame_slider_2 = QtWidgets.QSlider(self.frame_10)
        self.frame_slider_2.setMinimumSize(QtCore.QSize(1731, 0))
        self.frame_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider_2.setObjectName("frame_slider_2")
        self.verticalLayout_5.addWidget(self.frame_slider_2)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.tabWidget.addTab(self.TrackTab, "")
        self.FilterTab = QtWidgets.QWidget()
        self.FilterTab.setObjectName("FilterTab")
        self.frame_23 = QtWidgets.QFrame(self.FilterTab)
        self.frame_23.setGeometry(QtCore.QRect(0, 0, 1850, 920))
        self.frame_23.setMinimumSize(QtCore.QSize(1850, 900))
        self.frame_23.setMaximumSize(QtCore.QSize(1850, 1100))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frame_25 = QtWidgets.QFrame(self.frame_23)
        self.frame_25.setMinimumSize(QtCore.QSize(281, 900))
        self.frame_25.setMaximumSize(QtCore.QSize(281, 16777215))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setMinimumSize(QtCore.QSize(261, 211))
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 211))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_26)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_53 = QtWidgets.QLabel(self.frame_26)
        self.label_53.setObjectName("label_53")
        self.gridLayout_18.addWidget(self.label_53, 0, 0, 1, 1)
        self.find_outliers_btn = QtWidgets.QPushButton(self.frame_26)
        self.find_outliers_btn.setObjectName("find_outliers_btn")
        self.gridLayout_18.addWidget(self.find_outliers_btn, 0, 1, 1, 2)
        self.line_20 = QtWidgets.QFrame(self.frame_26)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_18.addWidget(self.line_20, 1, 0, 1, 3)
        self.fix_frames_table = QtWidgets.QTableWidget(self.frame_26)
        self.fix_frames_table.setObjectName("fix_frames_table")
        self.fix_frames_table.setColumnCount(0)
        self.fix_frames_table.setRowCount(0)
        self.gridLayout_18.addWidget(self.fix_frames_table, 2, 0, 1, 3)
        spacerItem16 = QtWidgets.QSpacerItem(152, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem16, 3, 0, 1, 2)
        self.add_frame_3_btn = QtWidgets.QPushButton(self.frame_26)
        self.add_frame_3_btn.setObjectName("add_frame_3_btn")
        self.gridLayout_18.addWidget(self.add_frame_3_btn, 3, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(self.frame_25)
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 271))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_27)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_54 = QtWidgets.QLabel(self.frame_27)
        self.label_54.setObjectName("label_54")
        self.gridLayout_16.addWidget(self.label_54, 0, 0, 1, 1)
        self.comp_combo_4 = QtWidgets.QComboBox(self.frame_27)
        self.comp_combo_4.setObjectName("comp_combo_4")
        self.gridLayout_16.addWidget(self.comp_combo_4, 0, 1, 1, 2)
        self.line_19 = QtWidgets.QFrame(self.frame_27)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_16.addWidget(self.line_19, 1, 0, 1, 3)
        self.label_58 = QtWidgets.QLabel(self.frame_27)
        self.label_58.setObjectName("label_58")
        self.gridLayout_16.addWidget(self.label_58, 2, 0, 1, 1)
        self.fps_spin = QtWidgets.QSpinBox(self.frame_27)
        self.fps_spin.setMinimumSize(QtCore.QSize(101, 26))
        self.fps_spin.setObjectName("fps_spin")
        self.gridLayout_16.addWidget(self.fps_spin, 2, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.frame_27)
        self.label_59.setObjectName("label_59")
        self.gridLayout_16.addWidget(self.label_59, 3, 0, 1, 1)
        self.n_deriv_kalman_spin = QtWidgets.QSpinBox(self.frame_27)
        self.n_deriv_kalman_spin.setMinimumSize(QtCore.QSize(101, 26))
        self.n_deriv_kalman_spin.setObjectName("n_deriv_kalman_spin")
        self.gridLayout_16.addWidget(self.n_deriv_kalman_spin, 3, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.frame_27)
        self.label_55.setObjectName("label_55")
        self.gridLayout_16.addWidget(self.label_55, 4, 0, 1, 2)
        self.quat_kalman_spin = QtWidgets.QDoubleSpinBox(self.frame_27)
        self.quat_kalman_spin.setMinimumSize(QtCore.QSize(101, 26))
        self.quat_kalman_spin.setObjectName("quat_kalman_spin")
        self.gridLayout_16.addWidget(self.quat_kalman_spin, 4, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.frame_27)
        self.label_56.setObjectName("label_56")
        self.gridLayout_16.addWidget(self.label_56, 5, 0, 1, 2)
        self.trans_kalman_spin = QtWidgets.QDoubleSpinBox(self.frame_27)
        self.trans_kalman_spin.setMinimumSize(QtCore.QSize(101, 26))
        self.trans_kalman_spin.setObjectName("trans_kalman_spin")
        self.gridLayout_16.addWidget(self.trans_kalman_spin, 5, 2, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.frame_27)
        self.label_57.setObjectName("label_57")
        self.gridLayout_16.addWidget(self.label_57, 6, 0, 1, 1)
        self.xi_kalman_spin = QtWidgets.QDoubleSpinBox(self.frame_27)
        self.xi_kalman_spin.setMinimumSize(QtCore.QSize(101, 26))
        self.xi_kalman_spin.setObjectName("xi_kalman_spin")
        self.gridLayout_16.addWidget(self.xi_kalman_spin, 6, 2, 1, 1)
        self.kalman_progress = QtWidgets.QProgressBar(self.frame_27)
        self.kalman_progress.setProperty("value", 24)
        self.kalman_progress.setObjectName("kalman_progress")
        self.gridLayout_16.addWidget(self.kalman_progress, 7, 0, 1, 3)
        spacerItem17 = QtWidgets.QSpacerItem(146, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem17, 8, 0, 1, 2)
        self.kalman_filter_btn = QtWidgets.QPushButton(self.frame_27)
        self.kalman_filter_btn.setObjectName("kalman_filter_btn")
        self.gridLayout_16.addWidget(self.kalman_filter_btn, 8, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_25)
        self.frame_28.setMinimumSize(QtCore.QSize(261, 361))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_28)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_63 = QtWidgets.QLabel(self.frame_28)
        self.label_63.setObjectName("label_63")
        self.gridLayout_20.addWidget(self.label_63, 4, 0, 1, 1)
        self.N_phi_spin = QtWidgets.QSpinBox(self.frame_28)
        self.N_phi_spin.setMinimumSize(QtCore.QSize(71, 26))
        self.N_phi_spin.setObjectName("N_phi_spin")
        self.gridLayout_20.addWidget(self.N_phi_spin, 2, 2, 2, 1)
        self.N_theta_spin = QtWidgets.QSpinBox(self.frame_28)
        self.N_theta_spin.setMinimumSize(QtCore.QSize(71, 26))
        self.N_theta_spin.setObjectName("N_theta_spin")
        self.gridLayout_20.addWidget(self.N_theta_spin, 4, 2, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.frame_28)
        self.label_61.setObjectName("label_61")
        self.gridLayout_20.addWidget(self.label_61, 3, 0, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.frame_28)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_20.addWidget(self.line_21, 1, 0, 2, 3)
        self.Legendre_progress = QtWidgets.QProgressBar(self.frame_28)
        self.Legendre_progress.setProperty("value", 24)
        self.Legendre_progress.setObjectName("Legendre_progress")
        self.gridLayout_20.addWidget(self.Legendre_progress, 11, 0, 1, 3)
        self.label_64 = QtWidgets.QLabel(self.frame_28)
        self.label_64.setObjectName("label_64")
        self.gridLayout_20.addWidget(self.label_64, 5, 0, 1, 2)
        self.label_65 = QtWidgets.QLabel(self.frame_28)
        self.label_65.setObjectName("label_65")
        self.gridLayout_20.addWidget(self.label_65, 6, 0, 1, 2)
        self.fit_wbs_btn = QtWidgets.QPushButton(self.frame_28)
        self.fit_wbs_btn.setObjectName("fit_wbs_btn")
        self.gridLayout_20.addWidget(self.fit_wbs_btn, 12, 1, 1, 2)
        self.N_xi_spin = QtWidgets.QSpinBox(self.frame_28)
        self.N_xi_spin.setMinimumSize(QtCore.QSize(71, 26))
        self.N_xi_spin.setObjectName("N_xi_spin")
        self.gridLayout_20.addWidget(self.N_xi_spin, 6, 2, 1, 1)
        self.N_eta_spin = QtWidgets.QSpinBox(self.frame_28)
        self.N_eta_spin.setMinimumSize(QtCore.QSize(71, 26))
        self.N_eta_spin.setObjectName("N_eta_spin")
        self.gridLayout_20.addWidget(self.N_eta_spin, 5, 2, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.frame_28)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout_20.addWidget(self.line_22, 7, 0, 2, 3)
        self.strk_angle_spin = QtWidgets.QDoubleSpinBox(self.frame_28)
        self.strk_angle_spin.setObjectName("strk_angle_spin")
        self.gridLayout_20.addWidget(self.strk_angle_spin, 8, 2, 2, 1)
        spacerItem18 = QtWidgets.QSpacerItem(167, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem18, 12, 0, 1, 1)
        self.phi_thresh_spin = QtWidgets.QDoubleSpinBox(self.frame_28)
        self.phi_thresh_spin.setObjectName("phi_thresh_spin")
        self.gridLayout_20.addWidget(self.phi_thresh_spin, 10, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.frame_28)
        self.label_60.setObjectName("label_60")
        self.gridLayout_20.addWidget(self.label_60, 0, 0, 1, 3)
        self.label_67 = QtWidgets.QLabel(self.frame_28)
        self.label_67.setObjectName("label_67")
        self.gridLayout_20.addWidget(self.label_67, 10, 0, 1, 2)
        self.label_66 = QtWidgets.QLabel(self.frame_28)
        self.label_66.setObjectName("label_66")
        self.gridLayout_20.addWidget(self.label_66, 9, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.frame_28)
        self.gridLayout_21.addWidget(self.frame_25, 0, 2, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        self.frame_24.setMinimumSize(QtCore.QSize(1543, 900))
        self.frame_24.setMaximumSize(QtCore.QSize(1650, 1100))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.x_plot_zoom = FilterPlots(self.frame_24)
        self.x_plot_zoom.setMinimumSize(QtCore.QSize(561, 191))
        self.x_plot_zoom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.x_plot_zoom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.x_plot_zoom.setObjectName("x_plot_zoom")
        self.gridLayout_17.addWidget(self.x_plot_zoom, 2, 1, 1, 1)
        self.q_plot = FilterPlots(self.frame_24)
        self.q_plot.setMinimumSize(QtCore.QSize(951, 191))
        self.q_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q_plot.setObjectName("q_plot")
        self.gridLayout_17.addWidget(self.q_plot, 0, 0, 1, 1)
        self.t_plot_zoom = FilterPlots(self.frame_24)
        self.t_plot_zoom.setMinimumSize(QtCore.QSize(561, 191))
        self.t_plot_zoom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.t_plot_zoom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.t_plot_zoom.setObjectName("t_plot_zoom")
        self.gridLayout_17.addWidget(self.t_plot_zoom, 1, 1, 1, 1)
        self.x_plot = FilterPlots(self.frame_24)
        self.x_plot.setMinimumSize(QtCore.QSize(951, 191))
        self.x_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.x_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.x_plot.setObjectName("x_plot")
        self.gridLayout_17.addWidget(self.x_plot, 2, 0, 1, 1)
        self.t_plot = FilterPlots(self.frame_24)
        self.t_plot.setMinimumSize(QtCore.QSize(951, 191))
        self.t_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.t_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.t_plot.setObjectName("t_plot")
        self.gridLayout_17.addWidget(self.t_plot, 1, 0, 1, 1)
        self.q_plot_zoom = FilterPlots(self.frame_24)
        self.q_plot_zoom.setMinimumSize(QtCore.QSize(561, 191))
        self.q_plot_zoom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q_plot_zoom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q_plot_zoom.setObjectName("q_plot_zoom")
        self.gridLayout_17.addWidget(self.q_plot_zoom, 0, 1, 1, 1)
        self.cost_plot_zoom = FilterPlots(self.frame_24)
        self.cost_plot_zoom.setMinimumSize(QtCore.QSize(561, 183))
        self.cost_plot_zoom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cost_plot_zoom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cost_plot_zoom.setObjectName("cost_plot_zoom")
        self.gridLayout_17.addWidget(self.cost_plot_zoom, 3, 1, 1, 1)
        self.cost_plot = FilterPlots(self.frame_24)
        self.cost_plot.setMinimumSize(QtCore.QSize(951, 183))
        self.cost_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cost_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cost_plot.setObjectName("cost_plot")
        self.gridLayout_17.addWidget(self.cost_plot, 3, 0, 1, 1)
        self.frame_35 = QtWidgets.QFrame(self.frame_24)
        self.frame_35.setMinimumSize(QtCore.QSize(1523, 100))
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_35)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_31 = QtWidgets.QFrame(self.frame_35)
        self.frame_31.setMinimumSize(QtCore.QSize(461, 51))
        self.frame_31.setMaximumSize(QtCore.QSize(461, 51))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_50 = QtWidgets.QLabel(self.frame_31)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_8.addWidget(self.label_50)
        self.movie_spin_3 = QtWidgets.QSpinBox(self.frame_31)
        self.movie_spin_3.setObjectName("movie_spin_3")
        self.horizontalLayout_8.addWidget(self.movie_spin_3)
        spacerItem19 = QtWidgets.QSpacerItem(21, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.label_51 = QtWidgets.QLabel(self.frame_31)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_8.addWidget(self.label_51)
        self.seq_spin_3 = QtWidgets.QSpinBox(self.frame_31)
        self.seq_spin_3.setObjectName("seq_spin_3")
        self.horizontalLayout_8.addWidget(self.seq_spin_3)
        spacerItem20 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.label_52 = QtWidgets.QLabel(self.frame_31)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_8.addWidget(self.label_52)
        self.frame_spin_3 = QtWidgets.QSpinBox(self.frame_31)
        self.frame_spin_3.setMinimumSize(QtCore.QSize(81, 20))
        self.frame_spin_3.setObjectName("frame_spin_3")
        self.horizontalLayout_8.addWidget(self.frame_spin_3)
        self.gridLayout_19.addWidget(self.frame_31, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(908, 16, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem21, 0, 1, 1, 1)
        self.filtered_trace_btn = QtWidgets.QFrame(self.frame_35)
        self.filtered_trace_btn.setMinimumSize(QtCore.QSize(564, 41))
        self.filtered_trace_btn.setMaximumSize(QtCore.QSize(651, 41))
        self.filtered_trace_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filtered_trace_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filtered_trace_btn.setObjectName("filtered_trace_btn")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.filtered_trace_btn)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.raw_trace_btn = QtWidgets.QRadioButton(self.filtered_trace_btn)
        self.raw_trace_btn.setObjectName("raw_trace_btn")
        self.horizontalLayout_3.addWidget(self.raw_trace_btn)
        self.raw_pred_trace_btn = QtWidgets.QRadioButton(self.filtered_trace_btn)
        self.raw_pred_trace_btn.setObjectName("raw_pred_trace_btn")
        self.horizontalLayout_3.addWidget(self.raw_pred_trace_btn)
        self.raw_filt_trace_btn = QtWidgets.QRadioButton(self.filtered_trace_btn)
        self.raw_filt_trace_btn.setObjectName("raw_filt_trace_btn")
        self.horizontalLayout_3.addWidget(self.raw_filt_trace_btn)
        self.filt_trace_btn = QtWidgets.QRadioButton(self.filtered_trace_btn)
        self.filt_trace_btn.setObjectName("filt_trace_btn")
        self.horizontalLayout_3.addWidget(self.filt_trace_btn)
        self.stroke_trace_btn = QtWidgets.QRadioButton(self.filtered_trace_btn)
        self.stroke_trace_btn.setObjectName("stroke_trace_btn")
        self.horizontalLayout_3.addWidget(self.stroke_trace_btn)
        self.gridLayout_19.addWidget(self.filtered_trace_btn, 0, 2, 1, 1)
        self.frame_30 = QtWidgets.QFrame(self.frame_35)
        self.frame_30.setMinimumSize(QtCore.QSize(211, 31))
        self.frame_30.setMaximumSize(QtCore.QSize(211, 41))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_62 = QtWidgets.QLabel(self.frame_30)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_6.addWidget(self.label_62)
        self.deriv_spin = QtWidgets.QSpinBox(self.frame_30)
        self.deriv_spin.setMinimumSize(QtCore.QSize(71, 20))
        self.deriv_spin.setObjectName("deriv_spin")
        self.horizontalLayout_6.addWidget(self.deriv_spin)
        self.gridLayout_19.addWidget(self.frame_30, 0, 3, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.frame_35)
        self.frame_29.setMinimumSize(QtCore.QSize(191, 41))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_68 = QtWidgets.QLabel(self.frame_29)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_7.addWidget(self.label_68)
        self.comp_combo_3 = QtWidgets.QComboBox(self.frame_29)
        self.comp_combo_3.setObjectName("comp_combo_3")
        self.horizontalLayout_7.addWidget(self.comp_combo_3)
        self.gridLayout_19.addWidget(self.frame_29, 0, 4, 1, 1)
        self.frame_slider_3 = QtWidgets.QSlider(self.frame_35)
        self.frame_slider_3.setMinimumSize(QtCore.QSize(1421, 16))
        self.frame_slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider_3.setObjectName("frame_slider_3")
        self.gridLayout_19.addWidget(self.frame_slider_3, 1, 0, 1, 5)
        self.gridLayout_17.addWidget(self.frame_35, 4, 0, 1, 2)
        self.gridLayout_21.addWidget(self.frame_24, 0, 0, 1, 1)
        self.tabWidget.addTab(self.FilterTab, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Select fligth sequence:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Calibration folder:"))
        self.label_5.setText(_translate("MainWindow", "Select movie folders:"))
        self.label_2.setText(_translate("MainWindow", "Sequence folder:"))
        self.load_seq_btn.setText(_translate("MainWindow", "load data"))
        self.select_seq_btn.setText(_translate("MainWindow", "select"))
        self.select_calib_btn.setText(_translate("MainWindow", "select"))
        self.label_6.setText(_translate("MainWindow", "trigger mode:"))
        self.label_7.setText(_translate("MainWindow", "Movie nr:"))
        self.label_8.setText(_translate("MainWindow", "Frame nr:"))
        self.label_33.setText(_translate("MainWindow", "Set crop window:"))
        self.label_34.setText(_translate("MainWindow", "Nu:"))
        self.label_35.setText(_translate("MainWindow", "Nv:"))
        self.man_select_btn.setText(_translate("MainWindow", "manual selection"))
        self.auto_select_btn.setText(_translate("MainWindow", "automatic selection"))
        self.label_3.setText(_translate("MainWindow", "Body threshold:"))
        self.label_14.setText(_translate("MainWindow", "Max dist COM:"))
        self.label_12.setText(_translate("MainWindow", "Min. seq length:"))
        self.label_36.setText(_translate("MainWindow", "Manual cropping:"))
        self.label_44.setText(_translate("MainWindow", "x center:"))
        self.label_45.setText(_translate("MainWindow", "y center:"))
        self.label_46.setText(_translate("MainWindow", "z center:"))
        self.label_47.setText(_translate("MainWindow", "Add mask:"))
        self.label_48.setText(_translate("MainWindow", "cam nr:"))
        self.add_mask_btn.setText(_translate("MainWindow", "add mask"))
        self.remove_masks_btn.setText(_translate("MainWindow", "remove masks"))
        self.label_40.setText(_translate("MainWindow", "Set uv-shift:"))
        self.label_41.setText(_translate("MainWindow", "cam nr:"))
        self.label_42.setText(_translate("MainWindow", "u-shift:"))
        self.label_43.setText(_translate("MainWindow", "v-shift:"))
        self.set_uv_shift_btn.setText(_translate("MainWindow", "set uv-shift"))
        self.label_13.setText(_translate("MainWindow", "Calculate cropped images:"))
        self.select_save_fldr_btn.setText(_translate("MainWindow", "select save folder"))
        self.calc_crop_seq_btn.setText(_translate("MainWindow", "calculate"))
        self.load_crop_seq_btn.setText(_translate("MainWindow", "load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataLoadTab), _translate("MainWindow", "Load data"))
        self.label_32.setText(_translate("MainWindow", "Outlier frames:"))
        self.label_37.setText(_translate("MainWindow", "Outlier index:"))
        self.update_outlier_btn.setText(_translate("MainWindow", "update outlier"))
        self.label_38.setText(_translate("MainWindow", "Auto fix outliers:"))
        self.auto_fix_btn.setText(_translate("MainWindow", "auto fix"))
        self.label_69.setText(_translate("MainWindow", "Train network on labels"))
        self.train_net_btn.setText(_translate("MainWindow", "train"))
        self.label_39.setText(_translate("MainWindow", "Add label to training data:"))
        self.add_lbl_btn.setText(_translate("MainWindow", "save label"))
        self.label_9.setText(_translate("MainWindow", "Movie nr:"))
        self.label_26.setText(_translate("MainWindow", "Seq nr:"))
        self.label_10.setText(_translate("MainWindow", "Frame nr:"))
        self.img_view_btn.setText(_translate("MainWindow", "img view"))
        self.seg_view_btn.setText(_translate("MainWindow", "seg view"))
        self.label_11.setText(_translate("MainWindow", "Load model:"))
        self.select_mdl_btn.setText(_translate("MainWindow", "select"))
        self.mdl_view_btn.setText(_translate("MainWindow", "model view"))
        self.off_view_btn.setText(_translate("MainWindow", "off"))
        self.single_view_btn.setText(_translate("MainWindow", "single view"))
        self.label_15.setText(_translate("MainWindow", "Model component:"))
        self.label_16.setText(_translate("MainWindow", "q_x:"))
        self.label_19.setText(_translate("MainWindow", "t_x:"))
        self.label_22.setText(_translate("MainWindow", "scale:"))
        self.label_17.setText(_translate("MainWindow", "q_y:"))
        self.label_20.setText(_translate("MainWindow", "t_y:"))
        self.label_23.setText(_translate("MainWindow", "xi:"))
        self.label_18.setText(_translate("MainWindow", "q_z:"))
        self.label_21.setText(_translate("MainWindow", "t_z:"))
        self.reset_state_btn.setText(_translate("MainWindow", "reset"))
        self.label_24.setText(_translate("MainWindow", "Load network:"))
        self.label_25.setText(_translate("MainWindow", "Network:"))
        self.label_27.setText(_translate("MainWindow", "Weights file:"))
        self.select_weights_btn.setText(_translate("MainWindow", "select"))
        self.predict_btn.setText(_translate("MainWindow", "predict"))
        self.label_28.setText(_translate("MainWindow", "Particle Swarm Optimization:"))
        self.label_29.setText(_translate("MainWindow", "Nr of particles:"))
        self.label_30.setText(_translate("MainWindow", "Nr of iterations:"))
        self.pso_search_btn.setText(_translate("MainWindow", "search"))
        self.label_31.setText(_translate("MainWindow", "Analyze sequences:"))
        self.load_tracked_btn.setText(_translate("MainWindow", "load "))
        self.label_49.setText(_translate("MainWindow", "batch size:"))
        self.analyze_btn.setText(_translate("MainWindow", "analyze"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TrackTab), _translate("MainWindow", "Track data"))
        self.label_53.setText(_translate("MainWindow", "Fix datapoints:"))
        self.find_outliers_btn.setText(_translate("MainWindow", "find outliers"))
        self.add_frame_3_btn.setText(_translate("MainWindow", "add frame"))
        self.label_54.setText(_translate("MainWindow", "Kalman filter:"))
        self.label_58.setText(_translate("MainWindow", "Fps (delta t):"))
        self.label_59.setText(_translate("MainWindow", "Nr derivatives:"))
        self.label_55.setText(_translate("MainWindow", "Quaternion filter:"))
        self.label_56.setText(_translate("MainWindow", "Translation filter:"))
        self.label_57.setText(_translate("MainWindow", "Xi filter:"))
        self.kalman_filter_btn.setText(_translate("MainWindow", "filter"))
        self.label_63.setText(_translate("MainWindow", "Nr polynomials theta:"))
        self.label_61.setText(_translate("MainWindow", "Nr polynomials phi:"))
        self.label_64.setText(_translate("MainWindow", "Nr polynomials eta:"))
        self.label_65.setText(_translate("MainWindow", "Nr polynomials xi:"))
        self.fit_wbs_btn.setText(_translate("MainWindow", "fit"))
        self.label_60.setText(_translate("MainWindow", "Legendre fit:"))
        self.label_67.setText(_translate("MainWindow", "phi threshold:"))
        self.label_66.setText(_translate("MainWindow", "Strokeplane angle:"))
        self.label_50.setText(_translate("MainWindow", "Movie nr:"))
        self.label_51.setText(_translate("MainWindow", "Seq nr:"))
        self.label_52.setText(_translate("MainWindow", "Frame nr:"))
        self.raw_trace_btn.setText(_translate("MainWindow", "raw data"))
        self.raw_pred_trace_btn.setText(_translate("MainWindow", "raw + prediction"))
        self.raw_filt_trace_btn.setText(_translate("MainWindow", "raw + filtered"))
        self.filt_trace_btn.setText(_translate("MainWindow", "filtered"))
        self.stroke_trace_btn.setText(_translate("MainWindow", "strokeplane"))
        self.label_62.setText(_translate("MainWindow", "Derivative:"))
        self.label_68.setText(_translate("MainWindow", "Component:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FilterTab), _translate("MainWindow", "Correct data"))

from .FilterPlots import FilterPlots
from .ImgViewer1 import ImgViewer1
from .ImgViewer2 import ImgViewer2
